# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'game.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(490, 610)
        MainWindow.setMinimumSize(QtCore.QSize(490, 610))
        MainWindow.setMaximumSize(QtCore.QSize(490, 610))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../PycharmProjects/GameOnPython/icons/Zhoolego-Material-Games.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 159, 255, 255), stop:1 rgba(236, 47, 75, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 159, 450, 431))
        self.frame.setStyleSheet("background-color: black;\n"
"border-radius: 10px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 30, 391, 371))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_1 = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_1.setEnabled(False)
        self.btn_1.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setFamily("Monaco")
        font.setPointSize(75)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.btn_1.setFont(font)
        self.btn_1.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_1.setMouseTracking(False)
        self.btn_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_1.setStyleSheet("QPushButton {\n"
"    background: white;\n"
"    border: 3px solid grey;\n"
"    border-radius: 15px;\n"
"    color: red;\n"
"}\n"
"QPushButton:hover {\n"
"    background: #e6e6e6;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background: white;\n"
"    border: 3px solid grey;\n"
"    border-radius: 15px;\n"
"}")
        self.btn_1.setText("")
        self.btn_1.setChecked(False)
        self.btn_1.setObjectName("btn_1")
        self.gridLayout.addWidget(self.btn_1, 0, 0, 1, 1)
        self.btn_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_2.setEnabled(False)
        self.btn_2.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(85)
        font.setBold(True)
        font.setWeight(75)
        self.btn_2.setFont(font)
        self.btn_2.setMouseTracking(False)
        self.btn_2.setStyleSheet("QPushButton {\n"
"    background: white;\n"
"    border: 3px solid grey;\n"
"    border-radius: 15px;\n"
"    color: blue;\n"
"}\n"
"QPushButton:hover {\n"
"    background: #e6e6e6;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background: white;\n"
"    border: 3px solid grey;\n"
"    border-radius: 15px;\n"
"}")
        self.btn_2.setText("")
        self.btn_2.setObjectName("btn_2")
        self.gridLayout.addWidget(self.btn_2, 0, 1, 1, 1)
        self.btn_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_3.setEnabled(False)
        self.btn_3.setMaximumSize(QtCore.QSize(120, 120))
        self.btn_3.setMouseTracking(False)
        self.btn_3.setStyleSheet("QPushButton {\n"
"    background: white;\n"
"    border: 3px solid grey;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover {\n"
"    background: #e6e6e6;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background: white;\n"
"    border: 3px solid grey;\n"
"    border-radius: 15px;\n"
"}")
        self.btn_3.setText("")
        self.btn_3.setObjectName("btn_3")
        self.gridLayout.addWidget(self.btn_3, 0, 2, 1, 1)
        self.btn_4 = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_4.setEnabled(False)
        self.btn_4.setMaximumSize(QtCore.QSize(120, 120))
        self.btn_4.setMouseTracking(False)
        self.btn_4.setStyleSheet("QPushButton {\n"
"    background: white;\n"
"    border: 3px solid grey;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover {\n"
"    background: #e6e6e6;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background: white;\n"
"    border: 3px solid grey;\n"
"    border-radius: 15px;\n"
"}")
        self.btn_4.setText("")
        self.btn_4.setObjectName("btn_4")
        self.gridLayout.addWidget(self.btn_4, 1, 0, 1, 1)
        self.btn_5 = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_5.setEnabled(False)
        self.btn_5.setMaximumSize(QtCore.QSize(120, 120))
        self.btn_5.setMouseTracking(False)
        self.btn_5.setStyleSheet("QPushButton {\n"
"    background: white;\n"
"    border: 3px solid grey;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover {\n"
"    background: #e6e6e6;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background: white;\n"
"    border: 3px solid grey;\n"
"    border-radius: 15px;\n"
"}")
        self.btn_5.setText("")
        self.btn_5.setObjectName("btn_5")
        self.gridLayout.addWidget(self.btn_5, 1, 1, 1, 1)
        self.btn_6 = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_6.setEnabled(False)
        self.btn_6.setMaximumSize(QtCore.QSize(120, 120))
        self.btn_6.setMouseTracking(False)
        self.btn_6.setStyleSheet("QPushButton {\n"
"    background: white;\n"
"    border: 3px solid grey;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover {\n"
"    background: #e6e6e6;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background: white;\n"
"    border: 3px solid grey;\n"
"    border-radius: 15px;\n"
"}")
        self.btn_6.setText("")
        self.btn_6.setFlat(False)
        self.btn_6.setObjectName("btn_6")
        self.gridLayout.addWidget(self.btn_6, 1, 2, 1, 1)
        self.btn_7 = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_7.setEnabled(False)
        self.btn_7.setMaximumSize(QtCore.QSize(120, 120))
        self.btn_7.setMouseTracking(False)
        self.btn_7.setStyleSheet("QPushButton {\n"
"    background: white;\n"
"    border: 3px solid grey;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover {\n"
"    background: #e6e6e6;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background: white;\n"
"    border: 3px solid grey;\n"
"    border-radius: 15px;\n"
"}")
        self.btn_7.setText("")
        self.btn_7.setObjectName("btn_7")
        self.gridLayout.addWidget(self.btn_7, 2, 0, 1, 1)
        self.btn_8 = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_8.setEnabled(False)
        self.btn_8.setMaximumSize(QtCore.QSize(120, 120))
        self.btn_8.setMouseTracking(False)
        self.btn_8.setStyleSheet("QPushButton {\n"
"    background: white;\n"
"    border: 3px solid grey;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover {\n"
"    background: #e6e6e6;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background: white;\n"
"    border: 3px solid grey;\n"
"    border-radius: 15px;\n"
"}")
        self.btn_8.setText("")
        self.btn_8.setObjectName("btn_8")
        self.gridLayout.addWidget(self.btn_8, 2, 1, 1, 1)
        self.btn_9 = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_9.setEnabled(False)
        self.btn_9.setMaximumSize(QtCore.QSize(120, 120))
        self.btn_9.setMouseTracking(False)
        self.btn_9.setStyleSheet("QPushButton {\n"
"    background: white;\n"
"    border: 3px solid grey;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover {\n"
"    background: #e6e6e6;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background: white;\n"
"    border: 3px solid grey;\n"
"    border-radius: 15px;\n"
"} ")
        self.btn_9.setText("")
        self.btn_9.setObjectName("btn_9")
        self.gridLayout.addWidget(self.btn_9, 2, 2, 1, 1)
        self.start_game = QtWidgets.QPushButton(self.centralwidget)
        self.start_game.setGeometry(QtCore.QRect(180, 20, 130, 120))
        self.start_game.setMinimumSize(QtCore.QSize(130, 120))
        self.start_game.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.start_game.setFont(font)
        self.start_game.setMouseTracking(False)
        self.start_game.setStyleSheet("QPushButton {\n"
"    background: #9bfc90;\n"
"    border: 5px solid black;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background: #72fc62;\n"
"    border: 3px solid black;\n"
"    border-radius: 5px;\n"
"}r")
        self.start_game.setObjectName("start_game")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 20, 151, 121))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background: none; color: white;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background: black; color: white;\n"
"border-radius: 20px;")
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(320, 20, 151, 121))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background: none; color: white;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background: black; color: white;\n"
"border-radius: 20px;")
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Хрестики-Нулики"))
        self.start_game.setText(_translate("MainWindow", "START"))
        self.layoutWidget1.setStyleSheet(_translate("MainWindow", "background: none;l"))
        self.label.setText(_translate("MainWindow", "ГРАВЕЦЬ ✖"))
        self.label_3.setText(_translate("MainWindow", "0"))
        self.layoutWidget2.setStyleSheet(_translate("MainWindow", "background: none;"))
        self.label_2.setText(_translate("MainWindow", "ГРАВЕЦЬ O"))
        self.label_4.setText(_translate("MainWindow", "0"))
